version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - spring-boot-react-network
    restart: always

  java-spring:
    build:
      context: ./java-spring
    ports:
      - "8080:8080"
    networks:
      - spring-boot-react-network
    restart: always

  react-app:
    build:
      context: ./react-app
    ports:
      - 3000:3000
    networks:
      - spring-boot-react-network
    volumes:
      - ./react-app:/app
      - /app/node_modules
    restart: always

networks:
  spring-boot-react-network:
    driver: bridge
